### ISSUE TITLE
train success ,run inference.py RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by qiufengyun** [xcmyz/LightSpeech#2]
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:453: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "inference.py", line 71, in <module>
    "results", words + str(num) + "waveglow.wav"))
  File "/data/soft/LightSpeech/waveglow/inference.py", line 36, in inference
    audio = waveglow.infer(mel, sigma=sigma)
  File "/data/soft/LightSpeech/glow.py", line 252, in infer
    spect = self.upsample(spect)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 640, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: CUDA out of memory. Tried to allocate 6.16 GiB (GPU 0; 7.92 GiB total capacity; 393.11 MiB already allocated; 5.48 GiB free; 704.89 MiB cached)

**Comment by xcmyz** [comment]
Use `with torch.eval():`
